version: '3.8'

services:
  backend:
    build: ./backend
    container_name: inventario-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_HOST: 192.168.100.100
      DB_PORT: 32768
      DB_NAME: papeleriadb
      DB_USER: postgres
      DB_PASSWORD: 30141644
      PORT: 3000

  frontend:
    build: .
    container_name: inventario-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - backend